[package]
name = "libav-player-demo"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

libav-player = { path = "../libav-player" }

[profile.release]
debug = true