[package]
name = "wgpu-player"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
tracing = { workspace = true }

wgpu = { workspace = true, features = ["parking_lot", "std", "wgsl"] }

# Local modules
libav-player = { workspace = true }